---
- hosts: aws-ireland

  tasks:
    - name: clean
      shell: rm -rf ~/deployments/stilles-protokol && mkdir -p ~/deployments/stilles-protokol

    - name: copy deployment artifacts
      copy:
        src: "stilles-protokol.tar.gz"
        dest: "~/deployments/stilles-protokol"

    - name: extract deployment
      shell: tar xzf ~/deployments/stilles-protokol/stilles-protokol.tar.gz -C ~/deployments/stilles-protokol

    - name: load docker image
      shell: docker load -i ~/deployments/stilles-protokol/image.tar

    - name: stop deployment
      shell: docker kill stilles-protokol || true
    
    - name: run app
      docker_container:
        name: stilles-protokol
        image: mesi/stilles-protokol
        auto_remove: yes
        ports:
        - "40103:80"
        env:
          MESI_SILENT_PROTOCOL_SilentProtocol__Password: "${MESI_SILENT_PROTOCOL_SilentProtocol__Password}"
          MESI_SILENT_PROTOCOL_ConnectionStrings__SilentProtocolDb: "${MESI_SILENT_PROTOCOL_ConnectionStrings__SilentProtocolDb}"
          MESI_SILENT_PROTOCOL_Discord__WebhookId: "${MESI_SILENT_PROTOCOL_Discord__WebhookId}"
          MESI_SILENT_PROTOCOL_Discord__WebhookToken: "${MESI_SILENT_PROTOCOL_Discord__WebhookToken}"
          MESI_SILENT_PROTOCOL_Oidc__Authority: "${MESI_SILENT_PROTOCOL_Oidc__Authority}"
          MESI_SILENT_PROTOCOL_Oidc__ClientId: "${MESI_SILENT_PROTOCOL_Oidc__ClientId}"
          MESI_SILENT_PROTOCOL_Oidc__Secret: "${MESI_SILENT_PROTOCOL_Oidc__Secret}"
