version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: silent-protocol-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "silent_protocol"
      