// <auto-generated />
using System;
using Mesi.Io.SilentProtocol.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Mesi.Io.SilentProtocol.Infrastructure.Db.Migrations
{
    [DbContext(typeof(SilentProtocolDbContext))]
    [Migration("20210122221724_AddCreatedAtRow")]
    partial class AddCreatedAtRow
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Mesi.Io.SilentProtocol.Domain.SilentProtocolEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Entry")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("entry");

                    b.Property<string>("Suspect")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suspect");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("time_stamp");

                    b.HasKey("Id");

                    b.ToTable("t_silent_protocol_entries");
                });
#pragma warning restore 612, 618
        }
    }
}
